# Generated by Django 5.1.7 on 2025-03-20 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='co_autor',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='book',
            name='data_devolucao',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='data_emprestimo',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='nome_emprestado',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='book',
            name='tempo_duracao',
            field=models.DateField(blank=True),
        ),
    ]
